#!/bin/bash
rm -rf bin lib
npx babel src --out-dir lib
cp -r src/view lib
npx pkg . --out-path bin
cp genesis.json bin
tar -zcvf bin/samplechain-linux.tgz bin/samplechain-linux bin/genesis.json
zip bin/samplechain-win.zip bin/samplechain-win.exe bin/genesis.json
zip bin/samplechain-macos.zip bin/samplechain-macos bin/genesis.json
